import tabelaEmolumentos from '../../../../tabela-emolumentos.json';
import { type SealBatch, type SealValues, } from '../types/types';

const getSealValues = (tipoAtoSelo: number): SealValues => {
    const emolumentoData = tabelaEmolumentos.find(item => item.id_selo === tipoAtoSelo);
    const emolumentos = emolumentoData?.valor_emolumento || 0;
    const taxaJudiciaria = emolumentoData?.valor_taxa_judiciaria || 0;
    const iss = parseFloat((emolumentos * 0.05).toFixed(2));
    const total = parseFloat((emolumentos + taxaJudiciaria + iss).toFixed(2));

    return {
        emolumentos,
        taxaJudiciaria,
        iss,
        total,
    };
};

export const mockSealBatches: SealBatch[] = [
    {
        id: 1,
        protocoloCompra: 'LOTE-2025-001',
        dataCompra: new Date(2025, 7, 5, 9, 30),
        quantidade: 10,
        intervaloNumeracao: '213600-213609',
        status: 'Ativo',
        descricao: '63 A II - Escritura completa, sobre o valor econômico do ato - até R$ 1.251,79',
        tipo_ato_selo: 2136,
        seals: [
            {
                sealNumber: '2136-0000',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0001',
                sealSituation: 'Utilizando',
                personName: 'Ana Clara Souza',
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0002',
                sealSituation: 'Utilizando',
                personName: 'Pedro Martins',
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0003',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0004',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0005',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0006',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0007',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0008',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2136-0009',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2136),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
        ],
    },
    {
        id: 2,
        protocoloCompra: 'LOTE-2025-002',
        dataCompra: new Date(2025, 7, 4, 14, 0),
        quantidade: 10,
        intervaloNumeracao: '300900-300909',
        status: 'Esgotado',
        descricao: '84 A I- Registro completo, com anotações e remissões de título, contrato ou outro documento',
        tipo_ato_selo: 3009,
        seals: [
            {
                sealNumber: '3009-0000',
                sealSituation: 'Exportado',
                personName: 'João Silva',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 15),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0001',
                sealSituation: 'Exportado',
                personName: 'Maria Oliveira',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 20),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0002',
                sealSituation: 'Exportado',
                personName: 'Carla Santos',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 25),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0003',
                sealSituation: 'Exportado',
                personName: 'Ricardo Costa',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 30),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0004',
                sealSituation: 'Exportado',
                personName: 'Juliana Pires',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 35),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0005',
                sealSituation: 'Exportado',
                personName: 'Carlos Mota',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 40),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0006',
                sealSituation: 'Exportado',
                personName: 'Bruna Rocha',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 45),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0007',
                sealSituation: 'Exportado',
                personName: 'Felipe Neves',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 50),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0008',
                sealSituation: 'Exportado',
                personName: 'Luiza Lima',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 14, 55),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '3009-0009',
                sealSituation: 'Exportado',
                personName: 'Guilherme Silva',
                sealValue: getSealValues(3009),
                exported: true,
                exportationDate: new Date(2025, 7, 4, 15, 0),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
        ],
    },
    {
        id: 3,
        protocoloCompra: 'LOTE-2025-003',
        dataCompra: new Date(2025, 7, 3, 11, 15),
        quantidade: 10,
        intervaloNumeracao: '213800-213809',
        status: 'Ativo',
        descricao: '63 A IV- Escritura completa, sobre o valor econômico do ato - até R$ 5.007,15',
        tipo_ato_selo: 2138,
        seals: [
            {
                sealNumber: '2138-0000',
                sealSituation: 'Utilizando',
                personName: 'Amanda Lima',
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0001',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0002',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0003',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0004',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0005',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0006',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0007',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0008',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2138-0009',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2138),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
        ],
    },
    {
        id: 4,
        protocoloCompra: 'LOTE-2025-004',
        dataCompra: new Date(2025, 6, 28, 17, 45),
        quantidade: 10,
        intervaloNumeracao: '213500-213509',
        status: 'Baixado',
        descricao: '63 A I - Escritura completa, sobre o valor econômico do ato – até R$ 625,89',
        tipo_ato_selo: 2135,
        seals: [
            {
                sealNumber: '2135-0000',
                sealSituation: 'Cancelado',
                personName: 'Rodrigo Nunes',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 17, 50),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0001',
                sealSituation: 'Cancelado',
                personName: 'Mariana Pires',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 17, 55),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0002',
                sealSituation: 'Cancelado',
                personName: 'Fernando Diniz',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 18, 0),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0003',
                sealSituation: 'Cancelado',
                personName: 'Joana Paes',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 18, 5),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0004',
                sealSituation: 'Cancelado',
                personName: 'Guilherme Castro',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 18, 10),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0005',
                sealSituation: 'Cancelado',
                personName: 'Daniela Souza',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 18, 15),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0006',
                sealSituation: 'Cancelado',
                personName: 'Rafael Fernandes',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 18, 20),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0007',
                sealSituation: 'Cancelado',
                personName: 'Renata Lemos',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 18, 25),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0008',
                sealSituation: 'Cancelado',
                personName: 'Pedro Pires',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 18, 30),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2135-0009',
                sealSituation: 'Cancelado',
                personName: 'Mariana Dias',
                sealValue: getSealValues(2135),
                exported: true,
                exportationDate: new Date(2025, 6, 28, 18, 35),
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
        ],
    },
    {
        id: 5,
        protocoloCompra: 'LOTE-2025-005',
        dataCompra: new Date(2025, 6, 15, 10, 0),
        quantidade: 10,
        intervaloNumeracao: '254500-254509',
        status: 'Ativo',
        descricao: '76 I – Registro até R$ 625,89',
        tipo_ato_selo: 2545,
        seals: [
            {
                sealNumber: '2545-0000',
                sealSituation: 'Redimensionado',
                personName: 'Carla Lima',
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: true,
                resizingDate: new Date(2025, 6, 20, 9, 0),
                linkedSeals: ['2545-0010'],
            },
            {
                sealNumber: '2545-0001',
                sealSituation: 'Redimensionado',
                personName: 'Lucas Rocha',
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: true,
                resizingDate: new Date(2025, 6, 20, 9, 10),
                linkedSeals: ['2545-0011'],
            },
            {
                sealNumber: '2545-0002',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2545-0003',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2545-0004',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2545-0005',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2545-0006',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2545-0007',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2545-0008',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
            {
                sealNumber: '2545-0009',
                sealSituation: 'Disponível',
                personName: null,
                sealValue: getSealValues(2545),
                exported: false,
                exportationDate: null,
                resized: false,
                resizingDate: null,
                linkedSeals: null,
            },
        ],
    },
];